language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
bundler_args: --without development
addons:
  code_climate:
    repo_token: 3c301208fc2fb3e0d2774e5cb90a4d42f65bb84b7a2443cca582bf7bea6f13b4a30ee50209bea31ef50f083d09fd65f96422e2cc5b14a61bec4a3a28c983382b
notifications:
  email:
    recipients:
      - innigerreto@gmail.com
    on_failure: change
    on_success: change
